### PR TITLE
fix headers

### LINKED ISSUE #32: Miscellaneous issues with existing "standards"
This is my first time coming across this project. In my opinion the concept of having standards for CC like this is comedic on its own, but I was at least hoping I'd see some decent organization and a more impressive arrangement of standards since the last time oeed contributed to them. I was disappointed. 
Below is the list of inconsistencies I found in the standards:

# CCSMB 1
The header defined by the standard is:
```md
*Author: Your Name <@yourgithub>*
*Version: v1.0.0
*Last updated: YYYY-MM-DD*
```
The header for CCSMB 1 itself does not follow this standard, opting to add an extra newline and a description, not defined by the standard:
```md
*Author: Tomodachi94 <@tomodachi94>*

*Version: v1.0.0*

*Last updated: 2022-11-07*

This RFC defines the protocol for defining and submitting a standard to the CCSMB.
```

Later in the file:
> The RFC should be written in a professional tone. Readers are expected to have a basic understanding of programming jargon and Lua programming.

bit of a nitpick but I feel like the term "programming jargon" coming right after "professional tone" completely side-steps the goal of the section. It could be written better.

# CCSMB 2
- Same issue as CCSMB 1, header newlines. 
- Version is not prefixed with a `v` like CCSMB 1 suggests.
- "Last updated" is now "Last revised", and the date has been left blank/with the template string, even though the version seemingly is not the first (1.0.1)

# CCSMB 6
- Same issue as CCSMB 1, header newlines.
- Same issue as CCSMB 1, header description.
- Same issue as CCSMB 2, version prefix.
- Same issue as CCSMB 2, "Last updated" -> "Last revised"

# CCSMB 7
- Same issue as CCSMB 1, header newlines.
- Same issue as CCSMB 1, header description.
- Same issue as CCSMB 2, version prefix.
- Same issue as CCSMB 2, "Last updated" -> "Last revised"

# CCSMB 10
- Same issue as CCSMB 2, template value for "Last updated".
- Version in header is the default template value instead of providing an actual version number.
- Standard has no fallback behavior for "compliant installers" when any of the setting values do not exist.

### PR DESCRIPTION
**Pull request by Rainb0wSkeppy**
fixes #32 mostly

### CODE REVIEW

**Comment by tomodachi94** [comment]
Does not fix #32, 32 points out numerous issues that aren't restricted to the headers' consistency

**Comment by Rainb0wSkeppy** [comment]
thats why i said mostly

**Comment by tomodachi94** [comment]
It makes the headers look like this:
image

I think CCSMB-1 should be modified [in the manner outlined here](https://github.com/CCSMB/Standards/issues/32#issuecomment-2028517704).

**Comment by MineRobber9000** [comment]
Try adding two spaces to the end of each line? That should preserve the line breaks without necessarily making each section of the header its own paragraph. (And then, obviously, edit CCSMB-1 to tell people to add the two spaces after each line.)

**Pull request closed without merging**
